const data = [{
        name: "Hayfa Gregory",
        phone: "1-851-448-2321",
        email: "aliquet@protonmail.org",
        address: "Ap #156-5674 Id Avenue",
        postalZip: "8991",
        country: "Morocco",
        img: `https://static.parade.com/wp-content/uploads/2021/12/cute-animals-5.jpg`,
    },
    {
        name: "Clarke Beck",
        phone: "(625) 671-6774",
        email: "nibh.aliquam.ornare@protonmail.edu",
        address: "Ap #433-7554 Bibendum Road",
        postalZip: "69-151",
        country: "Egypt",
        img: `https://static.parade.com/wp-content/uploads/2021/12/cute-animals-45.jpeg`,
    },
    {
        name: "Reese Hahn",
        phone: "(767) 383-8614",
        email: "vitae.purus.gravida@outlook.ca",
        address: "Ap #748-5695 Nec Rd.",
        postalZip: "13121",
        country: "Pakistan",
        img: `https://static.parade.com/wp-content/uploads/2021/12/cute-animals-9.jpg`,
    },
    {
        name: "Aimee Walter",
        phone: "(315) 446-5129",
        email: "quisque.ornare@icloud.ca",
        address: "P.O. Box 809, 462 Amet, Rd.",
        postalZip: "82645",
        country: "Chile",
        img: `https://static.parade.com/wp-content/uploads/2021/12/cute-animals-1.jpg`,
    },
    {
        name: "Nell Guerrero",
        phone: "(372) 866-5114",
        email: "vestibulum.neque.sed@aol.org",
        address: "Ap #633-6826 Duis Ave",
        postalZip: "17182",
        country: "Colombia",
        img: `https://static.parade.com/wp-content/uploads/2021/12/cute-animals-6.jpg`,
    },
];

export default data;